### ISSUE TITLE
Run within a docker compose

### ISSUE THREAD

**Issue by oreaird** [lychee3/fluent-bit-raspi#1]
When I try to use in a docker compose like so: 

```
fluentbit:
    image: lychee3/fluent-bit-raspi
    volumes:
      - ./fluent.conf:/conf/fluent.conf
    restart: unless-stopped
```

I get an error that 'ERROR: for fluentbit  Cannot create container for service fluentbit: No command specified'

any ideas?
